from typing import Optional, Union, Any, List
from pathlib import Path

from lightning.pytorch.loggers import WandbLogger as _WandbLogger


class WandbLogger(_WandbLogger):
    def __init__(
        self,
        name: Optional[str] = None,
        save_dir: Union[str, Path] = ".",
        version: Optional[str] = None,
        offline: bool = False,
        dir: Optional[Union[str, Path]] = None,
        id: Optional[str] = None,
        anonymous: Optional[bool] = None,
        project: str = "lightning_logs",
        log_model: Union[str, bool] = False,
        experiment = None,
        prefix: str = "",
        checkpoint_name: Optional[str] = None,
        job_type: Optional[str] = None,
        entity: Optional[str] = None,
        reinit: Optional[bool] = None,
        tags: Optional[List[str]] = None,
        group: Optional[str] = None,
        notes: Optional[str] = None,
        config_exclude_keys: Optional[List[str]] = None,
        config_include_keys: Optional[List[str]] = None,
        mode: Optional[str] = None,
        allow_val_change: Optional[bool] = None,
        resume: Optional[Union[bool, str]] = None,
        force: Optional[bool] = None,
        sync_tensorboard: Optional[bool] = None,
        monitor_gym: Optional[bool] = None,
        save_code: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(
            name=name,
            save_dir=save_dir,
            version=version,
            offline=offline,
            dir=dir,
            id=id,
            anonymous=anonymous,
            project=project,
            log_model=log_model,
            experiment=experiment,
            prefix=prefix,
            checkpoint_name=checkpoint_name,
            job_type=job_type,
            entity=entity,
            reinit=reinit,
            tags=tags,
            group=group,
            notes=notes,
            config_exclude_keys=config_exclude_keys,
            config_include_keys=config_include_keys,
            mode=mode,
            allow_val_change=allow_val_change,
            resume=resume,
            force=force,
            sync_tensorboard=sync_tensorboard,
            monitor_gym=monitor_gym,
            save_code=save_code,
            **kwargs,
        )
