data:
  class_path: x2r_3d.data.datamodules.SDFDataModule
  init_args:
    sdf_path: data/ShapeNetCoreV2/sdf/1006be65e7bc937e9141f9b58470d646.safetensors
    batch_size: 512
    num_workers: 64

model:
  class_path: x2r_3d.models.sdf.NeuralSDF
  init_args:
    grid:
      class_path: x2r_3d.models.grids.OctreeGrid
      init_args:
        accelstruct:
          class_path: x2r_3d.accelstructs.OctreeAS
          init_args:
            octree_path: data/ShapeNetCoreV2/octrees/1006be65e7bc937e9141f9b58470d646.pkl
        feature_dim: 64
        base_lod: 2
        num_lods: 3
        interpolation_type: linear
        aggregation_type: sum
        feature_std: 0.01
        feature_bias: 0.

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

trainer:
  devices: 1
  max_steps: 100_000

  val_check_interval: 10_000

  # logger:
  #   - class_path: x2r_3d.utils.logger.WandbLogger
  #     init_args:
  #       project: x2r-3d
  #       entity: viv
  #       name: debug

  callbacks:
    - class_path: ModelCheckpoint
      init_args:
        filename: "ckpt_{step:08d}"
        auto_insert_metric_name: False
        save_last: True
        save_top_k: -1
        every_n_train_steps: 5_000
    - LearningRateMonitor

  default_root_dir: wandb
  num_sanity_val_steps: 0

seed_everything: 2333
